### ISSUE TITLE
Eroare in Kodi instalat pe Android

### ISSUE THREAD

**Issue by atitudine** [moromete/plugin.video.streams#11]
Salut,

Felicitari pentru add-onul Streams! El merge excelent pe Raspberry Pi dar instalat pe un Kodi care ruleaza pe Android returneaza eroarea: Sreams
<type 'exceptions.OSError'>
[Errno 13] Permission denied

Toate cele bune,
Eugen

**Comment by viorel-m** [comment]
Rezolvat in 0.5.3, trebuie sa ai sop to http instalat in android
