### ISSUE TITLE
AceStream problem on Raspberry Pi

### ISSUE THREAD

**Issue by ovitemp** [moromete/plugin.video.streams#2]
Salutare Moromete,
Multumesc pentru acest excelent addon. L-am instalat pe Raspberry Pi2, OSMC si am reusit partial sa-l fac functional. Am instalat intai Plexus apoi am configurat path for sopcast:
          /home/osmc/.kodi/userdata/addon_data/program.plexus/sopcast
si totul este in regula pentru sopcast. 
AceStream functioneaza daca m-a conectez cu ssh si rulez:

~/.kodi/userdata/addon_data/program.plexus/acestream/start_acestream.sh --client-console --api-port 62062 --bind-all 

Ai putea sa adaugi cumva pornirea automata a acestream si oprirea procesului la terminarea stream-ului asa cum functioneaza in addonul Plexus?
Multumesc in numele tuturor utilizatorilor acestui addon

**Comment by moromete** [comment]
Salut,

Si eu il folosesc pe RPI2. Pentru sopcast ar trebui sa mearga direct cu binarele integrate fara path for sopcast.
In ceea ce priveste egine-ul de acestream o sa vad cum l-au integrat cei de la plexus si vedem ce se poate face. Merci de info. La momentul cand l-am scris nu exista varianta compilata a acestreamengine pentru RPI.

Numai bine!

**Comment by ovitemp** [comment]
Salutare,
Cred ca ai dreptate despre sopcast, am facut restore kodi pe un alt RPI2 si merge fara path (backup plugin din kodi nu tranfera toate setarile add-on-urilor). Cred ca a trebuit sa modific cararea pe sistemul meu dupa ce am incercat instalarea p2p-stream care include si acesta un sopcast ce nu functioneaza.
Abia astept upgrade-ul  pentru acestreame. Sunt sigur ca nu vei intampina greutati. 
O zi buna.

**Comment by ovitemp** [comment]
Salut moromete,
Avem vre-o speranta la un upgrade pentru pornirea automata a acetream?

**Comment by mp1111** [comment]
Salut Moromete,

Folosesc Kodi 17 (Beta) si astia au facut un recent update si de atunci nu mai merge nimic.

http://forum.kodi.tv/showthread.php?tid=250817&page=28

Fyi- post#410, 411, etc.

Popcormix spune ce e dela PR:

https://github.com/xbmc/xbmc/pull/8525

Crezi ca te poti uita- poate reusesti sa faci update la plugin sa mearga.

Multumesc mult.

**Comment by depes2016** [comment]
Salut Moromete vreo actualizare pentru Pi2. Inca nu merga canalele acestream cu raspberry pi 2

**Comment by moromete** [comment]
A fost adaugat suportul pentru plexus in 0.3.6. In setari la "engines" se poate folosi plexus pentru a rula sopcast sau ace. Nu toate stream-urile ace se pot rula cu versiunea de acestream engine implementata de plexus. Pentru acelea e necesara versiunea de acestream engine pentru windows > 3.1

**Comment by depes2016** [comment]
Multumesc Moromete pentru mesaj ! Multumesc si pentru addon, pentru timpul dedicat sa putem vedea programele romanesti aici departe de casa! 

    On Thursday, June 2, 2016 2:55 PM, moromete <notifications@github.com> wrote:
 

 A fost adaugat suportul pentru plexus in 0.3.6. In setari la "engines" se poate folosi plexus pentru a rula sopcast sau ace. Nu toate stream-urile ace se pot rula cu versiunea de acestream engine implementata de plexus. Pentru acelea e necesara versiunea de acestream engine pentru windows > 3.1—
