### ISSUE TITLE
Module pytz

### ISSUE THREAD

**Issue by RazTaz** [moromete/plugin.video.streams#20]
Eroarea:
No module named pytz
Please install module "pytz" or disable program guides from addon settings.

Apare de fiecare data cand deschid un post din lista de canale. Am incercat sa instalez modulul pytz separat, dar degeaba, desi imi apare ca modulul se instaleaza, streams scupia aceeasi eroare.

Nu am de unde sa dau disable program guides in setarile addon-ului.

plugin.video.streams 2.0.2 ruland pe OpenELEC 8.4/RPi2

**Comment by moromete** [comment]
Ar trebui ca acum sa nu mai ceara modulul pytz - update to 2.0.3

**Comment by RazTaz** [comment]
Da, acum merge bine. Confirm.

De asemenea, vreau sa iti multumesc mult pentru munca ta si pentru acest
plugin. Il folosesc de 6 ani de zile si - ca multi alti romani aflati in
strainatate - pentru mine asta e singurul mod in care pot sa vad imagini cu
ce se intimpla acasa.

Daca ai un cont pe paypal sau undeva, as vrea sa fac o mica donatie.

Cu stima,
Raz

**Comment by moromete** [comment]
Multumesc pentru aprecieri !
O vreme o sa mai aiba ceva bug-uri deoarece inca lucrez la o modalitate de a face link-urile comune intre utilizatori fara a avea un site dedicat ca pana acum. streams.magazinmixt.ro si tvdot.tk au fost inchise. Se pare ca varianta cu smtp va functiona. 
Pentru donatii verifica sectiunea de wiki.
