### ISSUE TITLE
Kodi 17 streams error- sopcast

### ISSUE THREAD

**Issue by mp1111** [moromete/plugin.video.streams#3]
Salut Moromete,

Folosesc Kodi 17 (Beta) si astia au facut un recent update si de atunci nu mai merge nimic.

http://forum.kodi.tv/showthread.php?tid=250817&page=28

Fyi- post#410, 411, etc.

Popcormix spune ce e dela PR:

xbmc/xbmc#8525

Crezi ca te poti uita- poate reusesti sa faci update la plugin sa mearga.

Multumesc mult.

**Comment by viorel-m** [comment]
Rezolvat
